#! /usr/bin/env python3
#-*- coding: utf-8 -*-
##
# Hermes's core
# Written by xlanor
##
import datetime

class Pmessage():
	def pmsg(self,address,username,ethplorerscan):
		msg = "🏠ETH Address: <b>"+address+"</b> \n"
		msg += "📋Generated by "+username+" at "
		msg += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
		msg += " +8GMT\n\n"
		usdlist = []
		sgdlist = []
		keylist = list(ethplorerscan.keys())
		try:
			keylist.remove('MTH') #problematic coins. emailed ethplorer dev.
		except:
			pass
		try:
			keylist.remove('CVC')
		except:
			pass
		try:
			keylist.remove('CND')
		except:
			pass
		calcmsg = ""
		countmsg = "💵You have the following in your wallet: \n"
		countlist = []
		for key in keylist:
			value = ethplorerscan[key]
			for each in value:
				if "balance" in each:
					balance = each["balance"]
				elif "name" in each:
					name = each["name"]
				elif "usd" in each:
					usd = each["usd"]
				elif "sgd" in each:
					sgd = each["sgd"]
			if usd != "-":
				usdval = round((float(balance) * float(usd)),2)
				usdlist.append(usdval)
			else:
				usdval = "-"
			if sgd != "-":
				sgdval = round((float(balance) * float(sgd)),2)
				sgdlist.append(sgdval)
			else:
				sgdval = "-"
			if usdval != "-":
				calcmsg += "💰<b>"
				calcmsg += str(round(balance,2))
				calcmsg += " "
				calcmsg += key
				calcmsg += "</b> is worth...\n"
				calcmsg += "🇸🇬SGD $"
				calcmsg += str(sgdval)
				calcmsg += "\n"
				calcmsg += "🇺🇸USD $"
				calcmsg += str(usdval)
				calcmsg += "\n"
				countlist.append(str(round(balance,2))+" "+key)
		countmsg += (", ".join(countlist))
		msg += countmsg
		msg += "\n\n"
		msg += calcmsg
		sgdtotal = round(sum(sgdlist),2)
		usdtotal = round(sum(usdlist),2)
		msg += "\n Your total portfolio value in 🇸🇬SGD is $"+str(sgdtotal)
		msg += "\n Your total portfolio value in 🇺🇸USD is $"+str(usdtotal)
		msg += "\n<i>* All values are rounded to 2 decimals and calculated using CryptoCompare</i>"
		msg += "\n<i>** USD -> SGD calculated with rates from Central European Bank</i>"
		msg += "\n<i>** If the token does not exist on CryptoCompare, it will not appear here.</i>"
		return msg